-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE inbox_email (
  email_id SERIAL NOT NULL,
  email_headers TEXT DEFAULT NULL,
  email_to TEXT NOT NULL,
  email_from TEXT NOT NULL,
  email_subject TEXT NOT NULL,
  email_body TEXT NOT NULL,
  email_timestamp TIMESTAMPTZ NOT NULL,
  email_read SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(email_id)
);

CREATE INDEX email_to ON inbox_email (email_to);
