-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/inbox_email (
  email_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  email_headers BLOB DEFAULT NULL, email_to BLOB NOT NULL,
  email_from BLOB NOT NULL, email_subject BLOB NOT NULL,
  email_body BLOB NOT NULL, email_timestamp BLOB NOT NULL,
  email_read SMALLINT DEFAULT 0 NOT NULL
);

CREATE INDEX email_to ON /*_*/inbox_email (email_to);
