-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/inbox_email (
  email_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  email_headers BLOB DEFAULT NULL,
  email_to VARBINARY(255) NOT NULL,
  email_from VARBINARY(255) NOT NULL,
  email_subject VARBINARY(2000) NOT NULL,
  email_body BLOB NOT NULL,
  email_timestamp BINARY(14) NOT NULL,
  email_read TINYINT(1) DEFAULT 0 NOT NULL,
  INDEX email_to (email_to),
  PRIMARY KEY(email_id)
) /*$wgDBTableOptions*/;
